#!/usr/bin/env python3
# gen_mix.py <c68k_ini.c> <hot list> <out.h>: the opcodes of each handler of
# the hot list (tools/c68ktest/hot995.txt, hottest first), for the
# instruction mix of core.c.  The opcode -> handler mapping is the one
# C68k_Init builds from c68k_opcode_jump_table (every entry in table order,
# a later one overriding an earlier one; the last entry is the default).
import random, re, sys

ini, hot, out = sys.argv[1:4]
ents = re.findall(r'\{&&op_(\w+)\s*,\s*(0x[0-9a-fA-F]+)\s*,\s*(0x[0-9a-fA-F]+)\}',
                  open(ini, encoding='latin-1').read())
ents = [(n, int(m, 16), int(v, 16)) for n, m, v in ents]
table = ['illegal'] * 0x10000
for name, mask, match in ents[:-1]:
    if mask == 0:
        continue
    # the entries come grouped by mask: enumerate the opcodes of each
    free = [b for b in range(16) if not (mask >> b) & 1]
    for k in range(1 << len(free)):
        op = match
        for i, b in enumerate(free):
            if (k >> i) & 1:
                op |= 1 << b
        if op & mask == match:
            table[op] = name
ops = {}
for op, name in enumerate(table):
    ops.setdefault(name, []).append(op)
names = [l.split()[0] for l in open(hot) if l.strip()]
rng = random.Random(68000)
lines = ['/* generated by gen_mix.py from %s and %s */' % (ini.split('/')[-1], hot.split('/')[-1]),
         'static const struct mix_handler { const char *name; int n; unsigned short op[32]; } mix_handlers[] = {']
for name in names:
    cand = ops.get(name, [])
    if len(cand) > 32:
        cand = sorted(rng.sample(cand, 32))
    lines.append('\t{ "%s", %d, { %s } },' % (name, len(cand), ', '.join('0x%04x' % o for o in cand) or '0'))
lines.append('};')
open(out, 'w').write('\n'.join(lines) + '\n')
