#!/usr/bin/env python3
# wdline.py <windraw.c> <out.c>: the line compositing part of x11/windraw.c
# (from the PSP FULLSCREEN_WIDTH block to the menu routines: the WD_*/wd_*
# helpers and WinDraw_DrawLine) as a file of its own for rend.c, built
# without PSP, SDL or the rest of windraw.c.
import sys
src, dst = sys.argv[1], sys.argv[2]
s = open(src, encoding='latin-1').read()
i = s.index('#ifdef PSP\n#ifdef FULLSCREEN_WIDTH')
j = s.index('/********** menu')
head = '''/* generated by tools/bench/wdline.py from x11/windraw.c */
#include "common.h"
#include "winx68k.h"
#include "bg.h"
#include "crtc.h"
#include "gvram.h"
#include "palette.h"
#include "tvram.h"

extern BYTE Debug_Text, Debug_Grp, Debug_Sp;
WORD *ScrBuf;
BYTE Draw_DrawFlag;
'''
open(dst, 'w', encoding='latin-1').write(head + s[i:j])
